# appBundle
image_store_app:
    resource: "@ImageStoreAppBundle/Resources/config/routing.yml"
    prefix:   /

# default
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# image_store_user
image_store_user_security:
    resource: "@ImageStoreUserBundle/Resources/config/routing/security.yml"
    prefix: /user

image_store_user_profile:
    resource: "@ImageStoreUserBundle/Resources/config/routing/profile.yml"
    prefix: /user/profile

image_store_user_register:
    resource: "@ImageStoreUserBundle/Resources/config/routing/registration.yml"
    prefix: /user/register

image_store_user_resetting:
    resource: "@ImageStoreUserBundle/Resources/config/routing/resetting.yml"
    prefix: /user/resetting

image_store_user_change_password:
    resource: "@ImageStoreUserBundle/Resources/config/routing/change_password.yml"
    prefix: /user/profile