
image_store_user_profile_show:
    path: /
    defaults: { _controller: "FOSUserBundle:Profile:show" }
    methods: "GET"

image_store_user_profile_edit:
    path: /edit
    defaults: { _controller: "FOSUserBundle:Profile:edit" }
