
image_store_user_security_login:
    path: /login
    defaults: { _controller: "FOSUserBundle:Security:login" }

image_store_user_security_check:
    path: /login_check
    defaults: { _controller: "FOSUserBundle:Security:check" }
    methods: "POST"

image_store_user_security_logout:
    path: /logout
    defaults: { _controller: "FOSUserBundle:Security:logout" }
