
image_store_user_system_admin_group_list:
    path: /list
    defaults: { _controller: "FOSUserBundle:Group:list" }
    methods: "GET"

image_store_user_system_admin_group_new:
    path: /new
    defaults: { _controller: "FOSUserBundle:Group:new" }

image_store_user_system_admin_group_show:
    path: /{groupName}
    defaults: { _controller: "FOSUserBundle:Group:show" }
    methods: "GET"

image_store_user_system_admin_group_edit:
    path: /{groupName}/edit
    defaults: { _controller: "FOSUserBundle:Group:edit" }

image_store_user_system_admin_group_delete:
    path: /{groupName}/delete
    defaults: { _controller: "FOSUserBundle:Group:delete" }
    methods: "GET"
